spring:
  datasource:
    # do NOT set password here; let Key Vault supply it
    url: ${spring-datasource-url}
    username: ${app-db-user}
    password: ${spring-datasource-password}
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        default_schema: northwinds
        format_sql: true
    open-in-view: false

  cloud:
    azure:
      keyvault:
        secret:
          property-sources:
            - endpoint: https://kv-northwinds-prod.vault.azure.net/