spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/northwinds
    username: modern_java_write
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        default_schema: northwinds
        format_sql: true
        show_sql: true
